In [3]:
import pandas as ped
import matplotlib.pyplot as plt
from datasets import load_dataset

c:\Users\User\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
dataset = load_dataset("lukebarousse/data_jobs")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [5]:
df = dataset['train'].to_pandas()

In [6]:
df.sample(5)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
611597,Data Analyst,Data Analyst - Full-time / Part-time,"Ridgefield Park, NJ",via Snagajob,Full-time,False,"New York, United States",2023-06-10 11:59:52,False,False,United States,NaN,NaN,NaN,Way Forward Staffing,"['sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
366226,Senior Data Engineer,Data Historian Engineer OSi Pi - Sr Associate,"Melbourne VIC, Australia",via LinkedIn,Contractor,False,Australia,2023-01-01 23:37:22,False,False,Australia,NaN,NaN,NaN,eTeam,"['windows', 'sharepoint']","{'analyst_tools': ['sharepoint'], 'os': ['wind..."
459332,Business Analyst,ANALYST BUSINESS INTEL SR,"Manila, Metro Manila, Philippines",via LinkedIn,NaN,False,Philippines,2023-04-22 14:15:34,False,False,Philippines,NaN,NaN,NaN,Pontoon Solutions,"['microstrategy', 'tableau', 'word', 'excel', ...","{'analyst_tools': ['microstrategy', 'tableau',..."
108782,Software Engineer,Development Engineer Engine Test Benches*,"Munderfing, Austria",via Recruit.net,Full-time,False,Austria,2023-02-08 00:29:41,True,False,Austria,NaN,NaN,NaN,KTM Group North America,NaN,NaN
667308,Data Analyst,Sr. Data Analyst - Full-time,"Sylmar, CA",via Snagajob,Full-time,False,"California, United States",2023-09-03 10:00:24,False,True,United States,hour,NaN,24.334999,Abbott Laboratories,"['sap', 'power bi', 'flow']","{'analyst_tools': ['sap', 'power bi'], 'other'..."

In [7]:
df.index.name = 'job_index'

In [8]:
df_belgium = df[df['job_country'] == 'Belgium']

In [9]:
df_belgium.reset_index(inplace=True)
df_belgium

,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,20,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,NaN,NaN,NaN,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'sci...","{'libraries': ['pandas', 'numpy', 'scikit-lear..."
1,120,Senior Data Engineer,Senior Azure Data Engineer,"Antwerp, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-05-04 13:23:35,True,False,Belgium,NaN,NaN,NaN,Entico,"['python', 'azure', 'databricks', 'spark', 'ju...","{'cloud': ['azure', 'databricks'], 'libraries'..."
2,131,Data Engineer,Cloud Data Engineer,"Mechelen, Belgium",via LinkedIn Belgium,Full-time,False,Belgium,2023-01-28 13:48:30,False,False,Belgium,NaN,NaN,NaN,Telenet,"['sql', 'cassandra', 'aws', 'hadoop', 'spark',...","{'analyst_tools': ['word'], 'cloud': ['aws'], ..."
3,148,Data Analyst,Tableau BI Developer,"Brussels, Belgium",via BR Proud Jobs,Contractor,False,Belgium,2023-03-02 13:14:19,True,False,Belgium,NaN,NaN,NaN,Apollo Solutions,"['python', 'sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
4,150,Senior Data Analyst,Senior Consultant Data & Analytics,Belgium,via LinkedIn,Full-time,False,Belgium,2023-12-09 13:44:56,False,False,Belgium,NaN,NaN,NaN,EY,['excel'],{'analyst_tools': ['excel']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12073,785388,Data Engineer,Data Engineer,"Charleroi, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-02 06:42:10,False,False,Belgium,NaN,NaN,NaN,Actemium,"['sql', 'crystal', 'sql server', 'oracle', 'vu...","{'analyst_tools': ['ssrs', 'power bi', 'qlik']..."
12074,785424,Business Analyst,Supply Chain Analyst,"Mechelen, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-02 06:42:00,False,False,Belgium,NaN,NaN,NaN,Dixon Supply Chain,NaN,NaN
12075,785460,Data Scientist,Data scientist,"Brussels, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-10 06:23:56,False,False,Belgium,NaN,NaN,NaN,RVA,NaN,NaN
12076,785505,Data Analyst,Marketing Data Assistant,"Brussels, Belgium",via Emplois Trabajo.org,Full-time,False,Belgium,2023-01-27 06:29:52,False,False,Belgium,NaN,NaN,NaN,EURACTIV,"['javascript', 'html', 'spark']","{'libraries': ['spark'], 'programming': ['java..."
12077,785518,Data Engineer,Data Engineer at Proton Therapy Leader,"Ottignies-Louvain-la-Neuve, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-10 06:24:10,False,False,Belgium,NaN,NaN,NaN,IBA,"['databricks', 'azure', 'airflow', 'terraform'...","{'cloud': ['databricks', 'azure'], 'libraries'..."

In [10]:
df_belgium.set_index('job_index', inplace=True)
df_belgium

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
20,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,NaN,NaN,NaN,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'sci...","{'libraries': ['pandas', 'numpy', 'scikit-lear..."
120,Senior Data Engineer,Senior Azure Data Engineer,"Antwerp, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-05-04 13:23:35,True,False,Belgium,NaN,NaN,NaN,Entico,"['python', 'azure', 'databricks', 'spark', 'ju...","{'cloud': ['azure', 'databricks'], 'libraries'..."
131,Data Engineer,Cloud Data Engineer,"Mechelen, Belgium",via LinkedIn Belgium,Full-time,False,Belgium,2023-01-28 13:48:30,False,False,Belgium,NaN,NaN,NaN,Telenet,"['sql', 'cassandra', 'aws', 'hadoop', 'spark',...","{'analyst_tools': ['word'], 'cloud': ['aws'], ..."
148,Data Analyst,Tableau BI Developer,"Brussels, Belgium",via BR Proud Jobs,Contractor,False,Belgium,2023-03-02 13:14:19,True,False,Belgium,NaN,NaN,NaN,Apollo Solutions,"['python', 'sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
150,Senior Data Analyst,Senior Consultant Data & Analytics,Belgium,via LinkedIn,Full-time,False,Belgium,2023-12-09 13:44:56,False,False,Belgium,NaN,NaN,NaN,EY,['excel'],{'analyst_tools': ['excel']}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785388,Data Engineer,Data Engineer,"Charleroi, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-02 06:42:10,False,False,Belgium,NaN,NaN,NaN,Actemium,"['sql', 'crystal', 'sql server', 'oracle', 'vu...","{'analyst_tools': ['ssrs', 'power bi', 'qlik']..."
785424,Business Analyst,Supply Chain Analyst,"Mechelen, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-02 06:42:00,False,False,Belgium,NaN,NaN,NaN,Dixon Supply Chain,NaN,NaN
785460,Data Scientist,Data scientist,"Brussels, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-10 06:23:56,False,False,Belgium,NaN,NaN,NaN,RVA,NaN,NaN
785505,Data Analyst,Marketing Data Assistant,"Brussels, Belgium",via Emplois Trabajo.org,Full-time,False,Belgium,2023-01-27 06:29:52,False,False,Belgium,NaN,NaN,NaN,EURACTIV,"['javascript', 'html', 'spark']","{'libraries': ['spark'], 'programming': ['java..."
785518,Data Engineer,Data Engineer at Proton Therapy Leader,"Ottignies-Louvain-la-Neuve, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-10 06:24:10,False,False,Belgium,NaN,NaN,NaN,IBA,"['databricks', 'azure', 'airflow', 'terraform'...","{'cloud': ['databricks', 'azure'], 'libraries'..."

In [17]:
df_belgium_jobs = df_belgium.pivot_table(
    index='job_title_short',
    values='salary_year_avg',
    aggfunc=['mean', 'min', 'max']
)
df_belgium_jobs.sort_values(by=('mean', 'salary_year_avg'), ascending=False)

                                     mean             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Data Scientist              119007.000000         56700.0        157500.0
Data Engineer               107451.772727         56700.0        147500.0
Data Analyst                 96395.625000         54988.0        165000.0
Senior Data Engineer         89100.000000         89100.0         89100.0
Machine Learning Engineer    83861.285714         72900.0        101029.0
Business Analyst             82620.000000         72900.0         89100.0
Senior Data Scientist        78300.000000         56700.0         89100.0
Software Engineer            58659.250000         44418.5         72900.0

In [18]:
df_belgium_jobs.sort_index()

                                     mean             min             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst             82620.000000         72900.0         89100.0
Data Analyst                 96395.625000         54988.0        165000.0
Data Engineer               107451.772727         56700.0        147500.0
Data Scientist              119007.000000         56700.0        157500.0
Machine Learning Engineer    83861.285714         72900.0        101029.0
Senior Data Engineer         89100.000000         89100.0         89100.0
Senior Data Scientist        78300.000000         56700.0         89100.0
Software Engineer            58659.250000         44418.5         72900.0